# Set up and display the board

 puts ""
 puts "		|	  | 	"
 puts "		|	  | 	"
 puts "		|	  | 	"
 puts "-----+-----+-----"
 puts "		|	  | 	"
 puts "		|	  | 	"
 puts "		|	  | 	"
 puts "-----+-----+-----"
 puts "		|	  | 	"
 puts "		|	  | 	"
 puts "		|	  | 	"
 puts ""